In [1]:
import os
import numpy as np
import mvpa2

bold_fname = os.path.join('..', 'data', 'ds105_raw', 'ds105', 'sub001', 'BOLD', 'task001_run001', 'bold.nii.gz')
# "E:\Users\Niall\Documents\Computer Science\FinalYearProject\data\ds105_raw\ds105\sub001\BOLD\task001_run002\bold.nii.gz"
bold_fname

E:\Anaconda3\lib\site-packages\mvpa2\base\dochelpers.py:167: FutureWarning: split() requires a non-empty pattern match.
  entries = __re_spliter1.split(paramdoc)


'..\\data\\ds105_raw\\ds105\\sub001\\BOLD\\task001_run001\\bold.nii.gz'

In [2]:
from mvpa2.tutorial_suite import *

mask_fname = os.path.join('..', 'data', 'ds105_raw', 'ds105', 'sub001', 'anatomy', 'highres001_brain_mask.nii.gz')
#"E:\Users\Niall\Documents\Computer Science\FinalYearProject\data\ds105_raw\ds105\sub001\anatomy\highres001_brain_mask.nii.gz"

ds = fmri_dataset(bold_fname)
len(ds) #samples

E:\Anaconda3\lib\site-packages\mvpa2\base\dochelpers.py:167: FutureWarning: split() requires a non-empty pattern match.
  entries = __re_spliter1.split(paramdoc)
E:\Anaconda3\lib\site-packages\mvpa2\base\dochelpers.py:167: FutureWarning: split() requires a non-empty pattern match.
  entries = __re_spliter1.split(paramdoc)
E:\Anaconda3\lib\site-packages\scipy\_lib\decorator.py:205: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  first = inspect.getargspec(caller)[0][0]  # first arg
E:\Anaconda3\lib\site-packages\scipy\optimize\nonlin.py:1502: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  args, varargs, varkw, defaults = inspect.getargspec(jac.__init__)
E:\Anaconda3\lib\site-packages\scipy\stats\_distn_infrastructure.py:636: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  sign = inspect.getargspec(self._stats)
E:\Anaconda3\lib\site-packages\scipy\stats\_distn_in

 * Please note: warnings are printed only once, but underlying problem might occur many times *


E:\Anaconda3\lib\site-packages\mvpa2\base\dochelpers.py:167: FutureWarning: split() requires a non-empty pattern match.
  entries = __re_spliter1.split(paramdoc)
E:\Anaconda3\lib\site-packages\sklearn\utils\fixes.py:64: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  if 'order' in inspect.getargspec(np.copy)[0]:
E:\Anaconda3\lib\site-packages\scipy\_lib\decorator.py:205: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  first = inspect.getargspec(caller)[0][0]  # first arg
E:\Anaconda3\lib\site-packages\mvpa2\base\dochelpers.py:167: FutureWarning: split() requires a non-empty pattern match.
  entries = __re_spliter1.split(paramdoc)
E:\Anaconda3\lib\site-packages\mvpa2\datasets\sources\skl_data.py:32: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  argnames, varargs, varkw, defaults = inspect.getargspec(fx)
E:\Anaconda3\lib\site-packages\mvpa2\base\dochelpers.py:16

121

In [3]:
ds.nfeatures #features

163840

In [4]:
ds.shape #samples / features

(121, 163840)

In [5]:
ds.sa.time_indices[:5]

array([0, 1, 2, 3, 4])

In [6]:
ds.sa.time_coords[:5]

array([ 0.,  1.,  2.,  3.,  4.])

In [7]:
ds.fa.voxel_indices[:5]

array([[0, 0, 0],
       [0, 0, 1],
       [0, 0, 2],
       [0, 0, 3],
       [0, 0, 4]])

In [8]:
'mapper' in ds.a # is there a mapper in the dataset

True

In [9]:
print(ds.a.mapper)

<FlattenMapper>


In [10]:
myfavs = [5, 6, 8, 10]
subds = ds[:, myfavs]
subds.shape

(121, 4)

In [11]:
print(subds.a.mapper)

<Chain: <Flatten>-<StaticFeatureSelection>>


In [12]:
print(subds)

<Dataset: 121x4@int16, <sa: time_coords,time_indices>, <fa: voxel_indices>, <a: imgaffine,imghdr,imgtype,mapper,voxel_dim,voxel_eldim>>


In [13]:
fwdtest = np.arange(12).reshape(4,3)
print(fwdtest)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [14]:
fmapped = subds.a.mapper.forward1(fwdtest)
fmapped.shape

ValueError: FlattenMapper has not been trained for data shape '(4, 3)' (known only '(40, 64, 64)').

In [15]:
data_set_path = os.path.join('..', 'data', 'ds105_raw', 'ds105')
dhandle = OpenFMRIDataset(data_set_path)
dhandle.get_subj_ids()

[1, 2, 3, 4, 5, 6]

In [16]:
dhandle.get_task_descriptions()

{1: 'object viewing'}

In [17]:
model = 1
subj = 1
run = 1
events = dhandle.get_bold_run_model(model, subj, run)
for ev in events[:2]: #get 2
    print(ev)

{'task': 1, 'intensity': 1, 'conset_idx': 0, 'duration': 0.5, 'onset_idx': 0, 'run': 1, 'onset': 12.0, 'condition': 'scissors'}
{'task': 1, 'intensity': 1, 'conset_idx': 1, 'duration': 0.5, 'onset_idx': 1, 'run': 1, 'onset': 14.0, 'condition': 'scissors'}


In [18]:
task = 1
fds = dhandle.get_bold_run_dataset(subj, task, run)
print(fds)

<Dataset: 121x163840@int16, <sa: run,subj,task,time_coords,time_indices>, <fa: voxel_indices>, <a: imgaffine,imghdr,imgtype,mapper,voxel_dim,voxel_eldim>>


In [19]:
from mvpa2.suite import *

dataset = ds
poly_detrend(dataset, chunks_attr='chunks')
dataset = dataset[dataset.sa.targets != 'rest']

sensana = OneWayAnova()

sens = sensana(dataset)


mri_args = {
    'cmap_bg' : 'gray',
    'cmap_overlay' : 'autumn', # YlOrRd_r # pl.cm.autumn
    'interactive' : cfg.getboolean('examples', 'interactive', True),
    }

fig = plot_lightbox(overlay=map2nifti(dataset, sens),
              vlim=(0, None), slices=range(25,29), **mri_args)

fig

KeyError: 'chunks'

In [20]:
ds.samples

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ..., 
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int16)

In [27]:

count = 0
for e in ds.features:
    if count == 10:
        break
    count = count + 1
    
    print(len(e))

AttributeError: 'Dataset' object has no attribute 'features'

In [ ]:
data = [[  1,  1, -1],
        [  2,  0,  0],
        [  3,  1,  1],
        [  4,  0, -1]]
new_ds = Dataset(data)
new_ds.shape

In [ ]:
new_ds.samples[1:-1]